In [1]:
import pandas as pd
from datetime import datetime, timedelta
from bs4 import BeautifulSoup as bs
import requests
from tqdm import tqdm

In [2]:
response = requests.get("https://api.opendota.com/api/leagues")
data = response.json()
league_df = pd.DataFrame(data)
league_df.to_csv('leagues.csv',index=False)

In [5]:
leagues = league_df[league_df['name'].str.contains('Division I Summ')]['leagueid'].values

In [14]:
teams_df = pd.DataFrame()

for league in leagues:
    response = requests.get(f"https://api.opendota.com/api/leagues/{league}/teams")
    data = response.json()
    teams_df = pd.concat([teams_df,pd.DataFrame(data)]).reset_index(drop=True)

In [15]:
teams_df

,team_id,rating,wins,losses,last_match_time,name,tag,logo_url
0,8687717,1237.010,26,9,1656770888,goonsquad,GS,https://steamusercontent-a.akamaihd.net/ugc/18...
1,2163,1357.780,1091,749,1656435484,Team Liquid,Liquid,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
2,8599101,1330.650,65,44,1657044485,Gaimin Gladiators,GG,https://steamusercontent-a.akamaihd.net/ugc/18...
3,8291895,1495.410,136,77,1656514805,Tundra Esports,Tundra,https://steamusercontent-a.akamaihd.net/ugc/17...
4,8605863,1377.360,71,37,1656950783,Entity,Entity,https://steamusercontent-a.akamaihd.net/ugc/18...
5,2586976,1576.690,778,480,1657029245,OG,OG,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
6,1838315,1352.360,973,483,1657044485,Team Secret,Secret,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
7,111474,1086.060,1174,929,1657029245,Alliance,Alliance,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
8,8376426,1170.550,107,90,1656544442,Wildcard Gaming,WC,https://steamusercontent-a.akamaihd.net/ugc/18...
9,7390454,1388.930,277,118,1656533589,Quincy Crew,QCY,https://steamusercontent-a.akamaihd.net/ugc/16...
10,8260983,1404.880,156,73,1656801910,TSM FTX,TSM FTX,https://steamusercontent-a.akamaihd.net/ugc/18...
11,8205424,939.114,70,106,1656544442,The Cut,TC,https://steamusercontent-a.akamaihd.net/ugc/16...
12,8728920,1240.150,27,10,1656533589,nouns,nouns,https://steamusercontent-a.akamaihd.net/ugc/18...
13,8261882,925.727,40,63,1657052648,felt,felt,https://steamusercontent-a.akamaihd.net/ugc/17...
14,39,1347.320,1233,749,1657052648,Evil Geniuses,EG,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
15,8607159,1013.800,46,35,1656792125,5RATFORCESTAFF,5RF,https://steamusercontent-a.akamaihd.net/ugc/18...
16,8261500,1412.460,123,114,1657018414,Xtreme Gaming,XG,https://steamusercontent-a.akamaihd.net/ugc/18...
17,8582076,1219.720,23,15,1656665597,Dandelion Esports Club,DEC,https://steamusercontent-a.akamaihd.net/ugc/18...
18,15,1386.910,1515,927,1656846440,PSG.LGD,PSG.LGD,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
19,4,1235.910,870,725,1656933027,EHOME,EHOME,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
20,7453020,1285.190,243,314,1657007717,Aster.Aries,Aries,https://steamusercontent-a.akamaihd.net/ugc/10...
21,6209166,1438.300,455,388,1657018414,Team Aster,Aster,https://steamusercontent-a.akamaihd.net/ugc/16...
22,6209804,1447.610,506,362,1656836014,Royal Never Give Up,RNG,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
23,726228,1267.310,1380,1005,1657007717,Vici Gaming,VG,https://steamcdn-a.akamaihd.net/apps/dota2/ima...

In [24]:
matches = teams_df['team_id'].values

matches_df = pd.DataFrame()

for team in matches:
    response = requests.get(f"https://api.opendota.com/api/teams/{team}/matches")
    data = response.json()
    matches_df = pd.concat([matches_df,pd.DataFrame(data)]).reset_index(drop=True)

In [25]:
matches_df

,match_id,radiant_win,radiant,duration,start_time,leagueid,league_name,cluster,opposing_team_id,opposing_team_name,opposing_team_logo
0,6644421405,False,True,2044,1656770888,14279,DPC WEU Division I Summer Tour - 2021/2022 - D...,273,2586976,OG,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
1,6644331178,True,False,2463,1656767567,14279,DPC WEU Division I Summer Tour - 2021/2022 - D...,273,2586976,OG,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
2,6644286608,True,False,3297,1656766503,14279,DPC WEU Division I Summer Tour - 2021/2022 - D...,273,2586976,OG,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
3,6638836003,False,False,2240,1656426142,14279,DPC WEU Division I Summer Tour - 2021/2022 - D...,273,111474,Alliance,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
4,6638731238,False,False,2372,1656422106,14279,DPC WEU Division I Summer Tour - 2021/2022 - D...,273,111474,Alliance,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
...,...,...,...,...,...,...,...,...,...,...,...
19632,241013480,False,False,1183,1373622005,52,REDBULL Esports Champion League 2013,231,728060,Esports-Muxi.CN,None
19633,240224923,True,True,3041,1373538628,52,REDBULL Esports Champion League 2013,231,5,INVICTUS GAMING,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
19634,240136233,False,True,2920,1373529652,52,REDBULL Esports Champion League 2013,231,416900,Orange.Neolution Esports,https://steamusercontent-a.akamaihd.net/ugc/61...
19635,240074559,False,True,2175,1373521733,52,REDBULL Esports Champion League 2013,231,15,PSG.LGD,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
19636,239249726,True,True,2192,1373432821,52,REDBULL Esports Champion League 2013,231,639906,DOTA2 positive energy,None

In [29]:
matches_df = matches_df.drop_duplicates(subset=['match_id']).reset_index(drop=True)

In [30]:
matches_df

,match_id,radiant_win,radiant,duration,start_time,leagueid,league_name,cluster,opposing_team_id,opposing_team_name,opposing_team_logo
0,6644421405,False,True,2044,1656770888,14279,DPC WEU Division I Summer Tour - 2021/2022 - D...,273,2586976,OG,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
1,6644331178,True,False,2463,1656767567,14279,DPC WEU Division I Summer Tour - 2021/2022 - D...,273,2586976,OG,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
2,6644286608,True,False,3297,1656766503,14279,DPC WEU Division I Summer Tour - 2021/2022 - D...,273,2586976,OG,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
3,6638836003,False,False,2240,1656426142,14279,DPC WEU Division I Summer Tour - 2021/2022 - D...,273,111474,Alliance,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
4,6638731238,False,False,2372,1656422106,14279,DPC WEU Division I Summer Tour - 2021/2022 - D...,273,111474,Alliance,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
...,...,...,...,...,...,...,...,...,...,...,...
16519,241977566,False,False,2055,1373717964,52,REDBULL Esports Champion League 2013,231,7,DK,https://steamusercontent-a.akamaihd.net/ugc/78...
16520,241013480,False,False,1183,1373622005,52,REDBULL Esports Champion League 2013,231,728060,Esports-Muxi.CN,None
16521,240224923,True,True,3041,1373538628,52,REDBULL Esports Champion League 2013,231,5,INVICTUS GAMING,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
16522,240136233,False,True,2920,1373529652,52,REDBULL Esports Champion League 2013,231,416900,Orange.Neolution Esports,https://steamusercontent-a.akamaihd.net/ugc/61...
16523,239249726,True,True,2192,1373432821,52,REDBULL Esports Champion League 2013,231,639906,DOTA2 positive energy,None

In [31]:
matches_df.to_csv("CN_NA_EU_matches.csv",index=False)